const cars = [
  {
    id: 1,
    name: "BMW M2",
    price: 63000,
    brand: "BMW",
    type: "sport",
    image: "../image/bmw_m2.jpg",
  },
  {
    id: 2,
    name: "BMW M3",
    price: 75000,
    brand: "BMW",
    type: "sport",
    image: "../image/bmw_m3.jpg",
  },
  {
    id: 3,
    name: "BMW M4",
    price: 80000,
    brand: "BMW",
    type: "sport",
    image: "../image/bmw_m4.jpg",
  },
  {
    id: 4,
    name: "BMW M5",
    price: 110000,
    brand: "BMW",
    type: "sport",
    image: "../image/bmw_m5.jpg",
  },
  {
    id: 5,
    name: "BMW M8",
    price: 140000,
    brand: "BMW",
    type: "sport",
    image: "../image/bmw_m8.jpg",
  },
  {
    id: 6,
    name: "BMW Z3",
    price: 45000,
    brand: "BMW",
    type: "sport",
    image: "../image/bmw_z3.jpg",
  },
  {
    id: 7,
    name: "BMW Z4",
    price: 55000,
    brand: "BMW",
    type: "sport",
    image: "../image/bmw_z4.jpg",
  },
  {
    id: 8,
    name: "BMW Z8",
    price: 200000,
    brand: "BMW",
    type: "sport",
    image: "../image/bmw_z8.jpg",
  },
  {
    id: 9,
    name: "BMW i8",
    price: 70000,
    brand: "BMW",
    type: "sport",
    image: "../image/bmw_i8.jpg",
  },
  {
    id: 10,
    name: "BMW E30 M3",
    price: 70000,
    brand: "BMW",
    type: "sport",
    image: "../image/bmw_e30_m3.jpg",
  },
  {
    id: 11,
    name: "BMW i4 M50",
    price: 65000,
    brand: "BMW",
    type: "sport",
    image: "../image/bmw_i4_m50.jpg",
  },
  {
    id: 12,
    name: "BMW E46 M3 CLS",
    price: 100000,
    brand: "BMW",
    type: "sport",
    image: "../image/bmw_e46_m3_cls.jpg",
  },
  {
    id: 13,
    name: "BMW 2002 Turbo",
    price: 80000,
    brand: "BMW",
    type: "sport",
    image: "../image/bmw_2002_turbo.jpg",
  },
  {
    id: 14,
    name: "BMW 507",
    price: 1000000,
    brand: "BMW",
    type: "sport",
    image: "../image/bmw_507.jpg",
  },
  {
    id: 15,
    name: "BMW 3 Series",
    price: 45000,
    brand: "BMW",
    type: "family",
    image: "../image/bmw_3_series.jpg",
  },
  {
    id: 16,
    name: "BMW 5 Series",
    price: 60000,
    brand: "BMW",
    type: "family",
    image: "../image/bmw_5_series.jpg",
  },
  {
    id: 17,
    name: "BMW 7 Series",
    price: 95000,
    brand: "BMW",
    type: "family",
    image: "../image/bmw_7_series.jpg",
  },
  {
    id: 18,
    name: "BMW i5",
    price: 65000,
    brand: "BMW",
    type: "family",
    image: "../image/bmw_i5.jpg",
  },
  {
    id: 19,
    name: "BMW X1",
    price: 40000,
    brand: "BMW",
    type: ["family", "suv"],
    image: "../image/bmw_x1.jpg",
  },
  {
    id: 20,
    name: "BMW X3",
    price: 50000,
    brand: "BMW",
    type: ["family", "suv"],
    image: "../image/bmw_x3.jpg",
  },
  {
    id: 21,
    name: "BMW X5",
    price: 65000,
    brand: "BMW",
    type: ["family", "suv"],
    image: "../image/bmw_x5.jpg",
  },
  {
    id: 22,
    name: "BMW X7",
    price: 80000,
    brand: "BMW",
    type: ["family", "suv"],
    image: "../image/bmw_x7.jpg",
  },
  {
    id: 23,
    name: "BMW iX",
    price: 85000,
    brand: "BMW",
    type: ["electric", "family"],
    image: "../image/bmw_ix.jpg",
  },
  {
    id: 24,
    name: "BMW iX3",
    price: 70000,
    brand: "BMW",
    type: ["electric", "family"],
    image: "../image/bmw_ix3.jpg",
  },
  {
    id: 25,
    name: "BMW iX4",
    price: 55000,
    brand: "BMW",
    type: ["electric", "family"],
    image: "../image/bmw_ix4.jpg",
  },
  {
    id: 26,
    name: "BMW iX7",
    price: 120000,
    brand: "BMW",
    type: ["electric", "family"],
    image: "../image/bmw_ix7.jpg",
  },
  {
    id: 27,
    name: "Porsche 911",
    price: 115000,
    brand: "Porsche",
    type: "sport",
    image: "../image/porsche_911.jpg",
  },
  {
    id: 28,
    name: "Porsche 718 Cayman",
    price: 70000,
    brand: "Porsche",
    type: "sport",
    image: "../image/porsche_718_cayman.jpg",
  },
  {
    id: 29,
    name: "Porsche 718 Boxster",
    price: 75000,
    brand: "Porsche",
    type: "sport",
    image: "../image/porsche_718_boxster.jpg",
  },
  {
    id: 30,
    name: "Porsche 911 Carrera",
    price: 115000,
    brand: "Porsche",
    type: "sport",
    image: "../image/porsche_911_carrera.jpg",
  },
  {
    id: 31,
    name: "Porsche 911 Carrera S",
    price: 130000,
    brand: "Porsche",
    type: "sport",
    image: "../image/porsche_911_carrera_s.jpg",
  },
  {
    id: 32,
    name: "Porsche 911 Turbo",
    price: 180000,
    brand: "Porsche",
    type: "sport",
    image: "../image/porsche_911_turbo.jpg",
  },
  {
    id: 33,
    name: "Porsche 911 Turbo S",
    price: 220000,
    brand: "Porsche",
    type: "sport",
    image: "../image/porsche_911_turbo_s.jpg",
  },
  {
    id: 34,
    name: "Porsche 911 GT3",
    price: 190000,
    brand: "Porsche",
    type: "sport",
    image: "../image/porsche_911_gt3.jpg",
  },
  {
    id: 35,
    name: "Porsche 911 GT3 RS",
    price: 230000,
    brand: "Porsche",
    type: "sport",
    image: "../image/porsche_911_gt3_rs.jpg",
  },
  {
    id: 36,
    name: "Porsche 718 cayman GT4 RS",
    price: 150000,
    brand: "Porsche",
    type: "sport",
    image: "../image/porsche_718_cayman_gt4_rs.jpg",
  },
  {
    id: 37,
    name: "Porsche 718 Boxster GTS",
    price: 95000,
    brand: "Porsche",
    type: "sport",
    image: "../image/porsche_718_boxster_gts.jpg",
  },
  {
    id: 38,
    name: "Porsche 718 Spyder",
    price: 110000,
    brand: "Porsche",
    type: "sport",
    image: "../image/porsche_718_spyder.jpg",
  },
  {
    id: 39,
    name: "Porsche 911 Targa",
    price: 140000,
    brand: "Porsche",
    type: "sport",
    image: "../image/porsche_911_targa.jpg",
  },
  {
    id: 40,
    name: "Porsche 911 Dakar",
    price: 230000,
    brand: "Porsche",
    type: "sport",
    image: "../image/porsche_911_dakar.jpg",
  },
  {
    id: 41,
    name: "Porsche Macan",
    price: 60000,
    brand: "Porsche",
    type: ["family", "suv"],
    image: "../image/porsche_macan.jpg",
  },
  {
    id: 42,
    name: "Porsche Macan T",
    price: 65000,
    brand: "Porsche",
    type: ["family", "suv"],
    image: "../image/porsche_macan_t.jpg",
  },
  {
    id: 43,
    name: "Porsche Macan S",
    price: 75000,
    brand: "Porsche",
    type: ["family", "suv"],
    image: "../image/porsche_macan_s.jpg",
  },
  {
    id: 44,
    name: "Porsche Macan GTS",
    price: 85000,
    brand: "Porsche",
    type: ["family", "suv"],
    image: "../image/porsche_macan_gts.jpg",
  },
  {
    id: 45,
    name: "Porsche Cayenne",
    price: 80000,
    brand: "Porsche",
    type: ["family", "suv"],
    image: "../image/porsche_cayenne.jpg",
  },
  {
    id: 46,
    name: "Porsche cayenne S",
    price: 95000,
    brand: "Porsche",
    type: ["family", "suv"],
    image: "../image/porsche_cayenne_s.jpg",
  },
  {
    id: 47,
    name: "Porsche cayenne GTS",
    price: 115000,
    brand: "Porsche",
    type: ["family", "suv"],
    image: "../image/porsche_cayenne_gts.jpg",
  },
  {
    id: 48,
    name: "Porsche cayenne Turbo s",
    price: 140000,
    brand: "Porsche",
    type: ["family", "suv"],
    image: "../image/porsche_cayenne_turbo_s.jpg",
  },
  {
    id: 49,
    name: "Porsche cayenne Turbo GT",
    price: 190000,
    brand: "Porsche",
    type: ["family", "suv"],
    image: "../image/porsche_cayenne_turbo_gt.jpg",
  },
  {
    id: 50,
    name: "Porsche cayenne coupe",
    price: 95000,
    brand: "Porsche",
    type: ["family", "suv"],
    image: "../image/porsche_cayenne_coupe.jpg",
  },
  {
    id: 51,
    name: "Porsche Taycan",
    price: 90000,
    brand: "Porsche",
    type: ["family", "electric"],
    image: "../image/porsche_taycan.jpg",
  },
  {
    id: 52,
    name: "Porsche Taycan 4S",
    price: 100000,
    brand: "Porsche",
    type: ["family", "electric"],
    image: "../image/porsche_taycan_4s.jpg",
  },
  {
    id: 53,
    name: "Porsche Taycan GTS",
    price: 140000,
    brand: "Porsche",
    type: ["family", "electric"],
    image: "../image/porsche_taycan_gts.jpg",
  },
  {
    id: 54,
    name: "Porsche Taycan Turbo",
    price: 160000,
    brand: "Porsche",
    type: ["family", "electric"],
    image: "../image/porsche_taycan_turbo.jpg",
  },
  {
    id: 55,
    name: "Porsche Taycan Turbo S",
    price: 200000,
    brand: "Porsche",
    type: ["family", "electric"],
    image: "../image/porsche_taycan_turbo_s.jpg",
  },
  {
    id: 56,
    name: "Porsche Taycan Cross Turismo",
    price: 110000,
    brand: "Porsche",
    type: ["family", "electric"],
    image: "../image/porsche_taycan_cross_turismo.jpg",
  },
  {
    id: 57,
    name: "Porsche Macan Electric",
    price: 100000,
    brand: "Porsche",
    type: ["family", "electric", "suv"],
    image: "../image/porsche_macan_electric.jpg",
  },
  {
    id: 58,
    name: "Mercedes AMG GT",
    price: 120000,
    brand: "Mercedes",
    type: "sport",
    image: "../image/mercedes_amg_gt.jpg",
  },
  {
    id: 59,
    name: "Mercedes AMG SL",
    price: 120000,
    brand: "Mercedes",
    type: "sport",
    image: "../image/mercedes_amg_sl.jpg",
  },
  {
    id: 60,
    name: "Mercedes AMG C63",
    price: 80000,
    brand: "Mercedes",
    type: "sport",
    image: "../image/mercedes_amg_c63.jpg",
  },
  {
    id: 61,
    name: "Mercedes AMG CLS C45",
    price: 60000,
    brand: "Mercedes",
    type: "sport",
    image: "../image/mercedes_amg_cls_c45.jpg",
  },
  {
    id: 62,
    name: "Mercedes A Class",
    price: 30000,
    brand: "Mercedes",
    type: "family",
    image: "../image/mercedes_a_class.jpg",
  },
  {
    id: 63,
    name: "Mercedes C Class",
    price: 40000,
    brand: "Mercedes",
    type: "family",
    image: "../image/mercedes_c_class.jpg",
  },
  {
    id: 64,
    name: "Mercedes e Class",
    price: 60000,
    brand: "Mercedes",
    type: "family",
    image: "../image/mercedes_e_class.jpg",
  },
  {
    id: 65,
    name: "Mercedes S Class",
    price: 110000,
    brand: "Mercedes",
    type: "family",
    image: "../image/mercedes_s_class.jpg",
  },
  {
    id: 66,
    name: "Mercedes Benz GLA",
    price: 40000,
    brand: "Mercedes",
    type: ["family", "suv"],
    image: "../image/mercedes_benz_gla.jpg",
  },
  {
    id: 67,
    name: "Mercedes Benz GLC",
    price: 60000,
    brand: "Mercedes",
    type: ["family", "suv"],
    image: "../image/mercedes_benz_glc.jpg",
  },
  {
    id: 68,
    name: "Mercedes Benz GLE",
    price: 80000,
    brand: "Mercedes",
    type: ["family", "suv"],
    image: "../image/mercedes_benz_gle.jpg",
  },
  {
    id: 69,
    name: "Mercedes Benz GLS",
    price: 100000,
    brand: "Mercedes",
    type: ["family", "suv"],
    image: "../image/mercedes_benz_gls.jpg",
  },
  {
    id: 70,
    name: "Mercedes Benz EQS",
    price: 100000,
    brand: "Mercedes",
    type: ["family", "electric"],
    image: "../image/mercedes_benz_eqs.jpg",
  },
  {
    id: 71,
    name: "Mercedes Benz EQE",
    price: 75000,
    brand: "Mercedes",
    type: ["family", "electric"],
    image: "../image/mercedes_benz_eqe.jpg",
  },
  {
    id: 72,
    name: "Mercedes Benz EQC",
    price: 80000,
    brand: "Mercedes",
    type: ["family", "electric"],
    image: "../image/mercedes_benz_eqc.jpg",
  },
  {
    id: 73,
    name: "Mercedes Benz EQB",
    price: 50000,
    brand: "Mercedes",
    type: ["family", "electric"],
    image: "../image/mercedes_benz_eqb.jpg",
  },
  {
    id: 74,
    name: "Audi R8",
    price: 160000,
    brand: "Audi",
    type: "sport",
    image: "../image/audi_r8.jpg",
  },
  {
    id: 75,
    name: "Audi RS3",
    price: 60000,
    brand: "Audi",
    type: "sport",
    image: "../image/audi_rs3.jpg",
  },
  {
    id: 76,
    name: "Audi RS5",
    price: 80000,
    brand: "Audi",
    type: "sport",
    image: "../image/audi_rs5.jpg",
  },
  {
    id: 77,
    name: "Audi TTS",
    price: 60000,
    brand: "Audi",
    type: "sport",
    image: "../image/audi_tts.jpg",
  },
  {
    id: 78,
    name: "Audi A3",
    price: 38000,
    brand: "Audi",
    type: "family",
    image: "../image/audi_a3.jpg",
  },
  {
    id: 79,
    name: "Audi A4",
    price: 40000,
    brand: "Audi",
    type: "family",
    image: "../image/audi_a4.jpg",
  },
  {
    id: 80,
    name: "Audi A6",
    price: 60000,
    brand: "Audi",
    type: "family",
    image: "../image/audi_a6.jpg",
  },
  {
    id: 81,
    name: "Audi A8",
    price: 90000,
    brand: "Audi",
    type: "family",
    image: "../image/audi_a8.jpg",
  },
  {
    id: 82,
    name: "Audi Q5",
    price: 50000,
    brand: "Audi",
    type: ["family", "suv"],
    image: "../image/audi_q5.jpg",
  },
  {
    id: 83,
    name: "Audi Q6",
    price: 58000,
    brand: "Audi",
    type: ["family", "suv"],
    image: "../image/audi_q6.jpg",
  },
  {
    id: 84,
    name: "Audi Q7",
    price: 65000,
    brand: "Audi",
    type: ["family", "suv"],
    image: "../image/audi_q7.jpg",
  },
  {
    id: 85,
    name: "Audi Q8",
    price: 75000,
    brand: "Audi",
    type: ["family", "suv"],
    image: "../image/audi_q8.jpg",
  },
  {
    id: 86,
    name: "Audi Q3",
    price: 38000,
    brand: "Audi",
    type: ["family", "suv"],
    image: "../image/audi_q3.jpg",
  },
  {
    id: 87,
    name: "Audi e-Tron GT",
    price: 105000,
    brand: "Audi",
    type: ["family", "electric"],
    image: "../image/audi_e_tron_gt.jpg",
  },
  {
    id: 88,
    name: "Audi RS e-Tron GT",
    price: 140000,
    brand: "Audi",
    type: ["family", "electric"],
    image: "../image/audi_rs_e_tron_gt.jpg",
  },
  {
    id: 89,
    name: "Audi Q4 e-Tron",
    price: 50000,
    brand: "Audi",
    type: ["family", "electric"],
    image: "../image/audi_q4_e_tron.jpg",
  },
  {
    id: 90,
    name: "Audi Q8 e-Tron",
    price: 75000,
    brand: "Audi",
    type: ["family", "electric"],
    image: "../image/audi_q8_e_tron.jpg",
  },
  {
    id: 91,
    name: "Lamborghini Huracan",
    price: 220000,
    brand: "Lamborghini",
    type: "sport",
    image: "../image/lamborghini_huracan.jpg",
  },
  {
    id: 92,
    name: "Lamborghini Huracan STO",
    price: 330000,
    brand: "Lamborghini",
    type: "sport",
    image: "../image/lamborghini_huracan_sto.jpg",
  },
  {
    id: 93,
    name: "Lamborghini Aventador",
    price: 440000,
    brand: "Lamborghini",
    type: "sport",
    image: "../image/lamborghini_aventador.jpg",
  },
  {
    id: 94,
    name: "Lamborghini Aventador SVJ",
    price: 650000,
    brand: "Lamborghini",
    type: "sport",
    image: "../image/lamborghini_aventador_svj.jpg",
  },
  {
    id: 95,
    name: "Lamborghini Revuelto",
    price: 600000,
    brand: "Lamborghini",
    type: "sport",
    image: "../image/lamborghini_revuelto.jpg",
  },
  {
    id: 96,
    name: "Lamborghini Sian",
    price: 3000000,
    brand: "Lamborghini",
    type: "sport",
    image: "../image/lamborghini_sian.jpg",
  },
  {
    id: 97,
    name: "Lamborghini Urus",
    price: 250000,
    brand: "Lamborghini",
    type: ["family", "suv"],
    image: "../image/lamborghini_urus.jpg",
  },
  {
    id: 98,
    name: "Ferrari 488 Pista",
    price: 350000,
    brand: "Ferrari",
    type: "sport",
    image: "../image/ferrari_488_pista.jpg",
  },
  {
    id: 99,
    name: "Ferrari F8 Tributo",
    price: 300000,
    brand: "Ferrari",
    type: "sport",
    image: "../image/ferrari_f8_tributo.jpg",
  },
  {
    id: 100,
    name: "Ferrari 296 GTB",
    price: 340000,
    brand: "Ferrari",
    type: "sport",
    image: "../image/ferrari_296_gtb.jpg",
  },
  {
    id: 101,
    name: "Ferrari SF90 Stradale",
    price: 500000,
    brand: "Ferrari",
    type: "sport",
    image: "../image/ferrari_sf90_stradale.jpg",
  },
  {
    id: 102,
    name: "Ferrari 812 Superfast",
    price: 400000,
    brand: "Ferrari",
    type: "sport",
    image: "../image/ferrari_812_superfast.jpg",
  },
  {
    id: 103,
    name: "Ferrari LaFerrari",
    price: 3000000,
    brand: "Ferrari",
    type: "sport",
    image: "../image/ferrari_laferrari.jpg",
  },
  {
    id: 104,
    name: "Ferrari GTC4Lusso",
    price: 300000,
    brand: "Ferrari",
    type: "family",
    image: "../image/ferrari_gtc4lusso.jpg",
  },
  {
    id: 105,
    name: "Ferrari 456 GT",
    price: 140000,
    brand: "Ferrari",
    type: "family",
    image: "../image/ferrari_456_gt.jpg",
  },
  {
    id: 106,
    name: "Ferrari Purosangue",
    price: 500000,
    brand: "Ferrari",
    type: ["family", "electric"],
    image: "../image/ferrari_purosangue.jpg",
  },
  {
    id: 107,
    name: "Nissan GT-R",
    price: 150000,
    brand: "Nissan",
    type: "sport",
    image: "../image/nissan_gt_r.jpg",
  },
  {
    id: 108,
    name: "Nissan Skyline GT-R",
    price: 80000,
    brand: "Nissan",
    type: "sport",
    image: "../image/nissan_skyline_gt_r.jpg",
  },
  {
    id: 109,
    name: "Nissan GTR r32",
    price: 50000,
    brand: "Nissan",
    type: "sport",
    image: "../image/nissan_gtr_r32.jpg",
  },
  {
    id: 110,
    name: "Nissan GTR r33",
    price: 60000,
    brand: "Nissan",
    type: "sport",
    image: "../image/nissan_gtr_r33.jpg",
  },
  {
    id: 111,
    name: "Nissan GTR r34",
    price: 100000,
    brand: "Nissan",
    type: "sport",
    image: "../image/nissan_gtr_r34.jpg",
  },
  {
    id: 112,
    name: "Nissan GTR r35",
    price: 150000,
    brand: "Nissan",
    type: "sport",
    image: "../image/nissan_gtr_r35.jpg",
  },
  {
    id: 113,
    name: "Nissan Sunny",
    price: 20000,
    brand: "Nissan",
    type: "family",
    image: "../image/nissan_sunny.jpg",
  },
  {
    id: 114,
    name: "Nissan Sentra",
    price: 22000,
    brand: "Nissan",
    type: "sport",
    image: "../image/nissan_sentra.jpg",
  },
  {
    id: 115,
    name: "Nissan Kicks",
    price: 25000,
    brand: "Nissan",
    type: ["family", "suv"],
    image: "../image/nissan_kicks.jpg",
  },
  {
    id: 116,
    name: "Nissan Qashqai",
    price: 30000,
    brand: "Nissan",
    type: ["family", "suv"],
    image: "../image/nissan_qashqai.jpg",
  },
  {
    id: 117,
    name: "Nissan Patrol",
    price: 70000,
    brand: "Nissan",
    type: ["family", "suv"],
    image: "../image/nissan_patrol.jpg",
  },
  {
    id: 118,
    name: "Nissan Pathfinder",
    price: 40000,
    brand: "Nissan",
    type: ["family", "suv"],
    image: "../image/nissan_pathfinder.jpg",
  },
  {
    id: 119,
    name: "Nissan X-Trail",
    price: 30000,
    brand: "Nissan",
    type: ["family", "suv"],
    image: "../image/nissan_x_trail.jpg",
  },
  {
    id: 120,
    name: "Nissan Leaf",
    price: 35000,
    brand: "Nissan",
    type: ["family", "electric"],
    image: "../image/nissan_leaf.jpg",
  },
  {
    id: 121,
    name: "Nissan Ariya",
    price: 50000,
    brand: "Nissan",
    type: ["family", "electric"],
    image: "../image/nissan_ariya.jpg",
  },
  {
    id: 122,
    name: "Volkswagen Golf GTI",
    price: 35000,
    brand: "Volkswagen",
    type: "sport",
    image: "../image/volkswagen_golf_gti.jpg",
  },
  {
    id: 123,
    name: "Volkswagen Golf R",
    price: 45000,
    brand: "Volkswagen",
    type: "sport",
    image: "../image/volkswagen_golf_r.jpg",
  },
  {
    id: 124,
    name: "Volkswagen Polo GTI",
    price: 30000,
    brand: "Volkswagen",
    type: "sport",
    image: "../image/volkswagen_polo_gti.jpg",
  },
  {
    id: 125,
    name: "Volkswagen Scirocco R",
    price: 25000,
    brand: "Volkswagen",
    type: "sport",
    image: "../image/volkswagen_scirocco_r.jpg",
  },
  {
    id: 126,
    name: "Volkswagen Polo",
    price: 15000,
    brand: "Volkswagen",
    type: "family",
    image: "../image/volkswagen_polo.jpg",
  },
  {
    id: 127,
    name: "Volkswagen Golf",
    price: 25000,
    brand: "Volkswagen",
    type: "family",
    image: "../image/volkswagen_golf.jpg",
  },
  {
    id: 128,
    name: "Volkswagen Jetta",
    price: 15000,
    brand: "Volkswagen",
    type: "family",
    image: "../image/volkswagen_jetta.jpg",
  },
  {
    id: 129,
    name: "Volkswagen Passat",
    price: 30000,
    brand: "Volkswagen",
    type: "family",
    image: "../image/volkswagen_passat.jpg",
  },
  {
    id: 130,
    name: "Volkswagen T-Cross",
    price: 20000,
    brand: "Volkswagen",
    type: ["family", "suv"],
    image: "../image/volkswagen_t_cross.jpg",
  },
  {
    id: 131,
    name: "Volkswagen T-Roc",
    price: 25000,
    brand: "Volkswagen",
    type: ["family", "suv"],
    image: "../image/volkswagen_t_roc.jpg",
  },
  {
    id: 132,
    name: "Volkswagen Tiguan",
    price: 30000,
    brand: "Volkswagen",
    type: ["family", "suv"],
    image: "../image/volkswagen_tiguan.jpg",
  },
  {
    id: 133,
    name: "Volkswagen Touareg",
    price: 60000,
    brand: "Volkswagen",
    type: ["family", "suv"],
    image: "../image/volkswagen_touareg.jpg",
  },
  {
    id: 134,
    name: "Volkswagen ID.3",
    price: 35000,
    brand: "Volkswagen",
    type: ["family", "electric"],
    image: "../image/volkswagen_id_3.jpg",
  },
  {
    id: 135,
    name: "Volkswagen ID.4",
    price: 40000,
    brand: "Volkswagen",
    type: ["family", "electric"],
    image: "../image/volkswagen_id_4.jpg",
  },
  {
    id: 136,
    name: "Volkswagen ID.5",
    price: 45000,
    brand: "Volkswagen",
    type: ["family", "electric"],
    image: "../image/volkswagen_id_5.jpg",
  },
  {
    id: 137,
    name: "McLaren 570S",
    price: 200000,
    brand: "McLaren",
    type: "sport",
    image: "../image/mclaren_570s.jpg",
  },
  {
    id: 138,
    name: "McLaren 600LT",
    price: 250000,
    brand: "McLaren",
    type: "sport",
    image: "../image/mclaren_600lt.jpg",
  },
  {
    id: 139,
    name: "McLaren 720S",
    price: 300000,
    brand: "McLaren",
    type: "sport",
    image: "../image/mclaren_720s.jpg",
  },
  {
    id: 140,
    name: "McLaren 765LT",
    price: 400000,
    brand: "McLaren",
    type: "sport",
    image: "../image/mclaren_765LT.jpg",
  },
  {
    id: 141,
    name: "McLaren Artura",
    price: 250000,
    brand: "McLaren",
    type: ["sport", "electric"],
    image: "../image/mclaren_Artura.jpg",
  },
  {
    id: 142,
    name: "McLaren P1",
    price: 1500000,
    brand: "McLaren",
    type: ["sport", "electric"],
    image: "../image/mclaren_p1.jpg",
  },
  {
    id: 143,
    name: "McLaren Senna",
    price: 1000000,
    brand: "McLaren",
    type: "sport",
    image: "../image/mclaren_senna.jpg",
  },
  {
    id: 144,
    name: "Aston Martin Vantage",
    price: 180000,
    brand: "Aston Martin",
    type: "sport",
    image: "../image/aston_martin_vantage.jpg",
  },
  {
    id: 145,
    name: "Aston Martin DB11",
    price: 200000,
    brand: "Aston Martin",
    type: "sport",
    image: "../image/aston_martin_db11.jpg",
  },
  {
    id: 146,
    name: "Aston Martin DBS Superleggera",
    price: 300000,
    brand: "Aston Martin",
    type: "sport",
    image: "../image/aston_martin_dbs_supperleggera.jpg",
  },
  {
    id: 147,
    name: "Aston Martin Valkyrie",
    price: 3000000,
    brand: "Aston Martin",
    type: ["sport", "electric"],
    image: "../image/aston_martin_valkyrie.jpg",
  },
  {
    id: 148,
    name: "Aston Martin Rapide",
    price: 200000,
    brand: "Aston Martin",
    type: "family",
    image: "../image/aston_martin_Rapide.jpg",
  },
  {
    id: 149,
    name: "Aston Martin DBX",
    price: 200000,
    brand: "Aston Martin",
    type: ["family", "suv"],
    image: "../image/aston_martin_dbx.jpg",
  },
  {
    id: 150,
    name: "Aston Martin DBX707",
    price: 250000,
    brand: "Aston Martin",
    type: ["family", "suv"],
    image: "../image/aston_martin_dbx707.jpg",
  },
  {
    id: 151,
    name: "Aston Martin Valhalla",
    price: 800000,
    brand: "Aston Martin",
    type: "electric",
    image: "../image/aston_martin_valhalla.jpg",
  },
  {
    id: 152,
    name: "Pagani Zonda",
    price: 2000000,
    brand: "Pagani",
    type: "sport",
    image: "../image/pagani_zonda.jpg",
  },
  {
    id: 153,
    name: "Pagani Zonda R",
    price: 6000000,
    brand: "Pagani",
    type: "sport",
    image: "../image/pagani_zonda_r.jpg",
  },
  {
    id: 154,
    name: "Pagani Huayra",
    price: 3000000,
    brand: "Pagani",
    type: "sport",
    image: "../image/pagani_huayra.jpg",
  },
  {
    id: 155,
    name: "Pagani Huayra BC",
    price: 4000000,
    brand: "Pagani",
    type: "sport",
    image: "../image/pagani_huayra_bc.jpg",
  },
  {
    id: 156,
    name: "Pagani Utopoa",
    price: 2500000,
    brand: "Pagani",
    type: "sport",
    image: "../image/pagani_utopoa.jpg",
  },
  {
    id: 157,
    name: "Maserati MC20",
    price: 200000,
    brand: "Maserati",
    type: "sport",
    image: "../image/maserati_MC20.jpg",
  },
  {
    id: 158,
    name: "Maserati MC20 Cielo",
    price: 260000,
    brand: "Maserati",
    type: "sport",
    image: "../image/maserati_mc20_cielo.jpg",
  },
  {
    id: 159,
    name: "Maserati GranTurismo",
    price: 150000,
    brand: "Maserati",
    type: "sport",
    image: "../image/maserati_granturismo.jpg",
  },
  {
    id: 160,
    name: "Maserati GranCabrio",
    price: 150000,
    brand: "Maserati",
    type: "sport",
    image: "../image/maserati_grancabrio.jpg",
  },
  {
    id: 161,
    name: "Maserati Ghibli",
    price: 80000,
    brand: "Maserati",
    type: "family",
    image: "../image/maserati_ghibli.jpg",
  },
  {
    id: 162,
    name: "Maserati quattroporte",
    price: 100000,
    brand: "Maserati",
    type: "family",
    image: "../image/maserati_quattroporte.jpg",
  },
  {
    id: 163,
    name: "Maserati Levante",
    price: 100000,
    brand: "Maserati",
    type: ["family", "suv"],
    image: "../image/maserati_levante.jpg",
  },
  {
    id: 164,
    name: "Maserati Grecale",
    price: 800000,
    brand: "Maserati",
    type: ["family", "suv"],
    image: "../image/maserati_grecale.jpg",
  },
  {
    id: 165,
    name: "Maserati GranTurismo Folgore",
    price: 190000,
    brand: "Maserati",
    type: "electric",
    image: "../image/maserati_granTurismo_folgore.jpg",
  },
  {
    id: 166,
    name: "Maserati Grecale Folgore",
    price: 100000,
    brand: "Maserati",
    type: "electric",
    image: "../image/maserati_grecale_folgore.jpg",
  },
  {
    id: 167,
    name: "Koenigsegg Jesko",
    price: 3000000,
    brand: "Koenigsegg",
    type: "sport",
    image: "../image/koenigsegg_jesko.jpg",
  },
  {
    id: 168,
    name: "Koenigsegg Jesko Absolut",
    price: 3500000,
    brand: "Koenigsegg",
    type: "sport",
    image: "../image/koenigsegg_jesko_absolut.jpg",
  },
  {
    id: 169,
    name: "Koenigsegg Agera RS",
    price: 3000000,
    brand: "Koenigsegg",
    type: "sport",
    image: "../image/koenigsegg_agera_rs.jpg",
  },
  {
    id: 170,
    name: "Koenigsegg Regera",
    price: 2000000,
    brand: "Koenigsegg",
    type: ["sport", "electric"],
    image: "../image/koenigsegg_regera.jpg",
  },
  {
    id: 171,
    name: "Koenigsegg Gemera",
    price: 2000000,
    brand: "Koenigsegg",
    type: ["family", "electric"],
    image: "../image/koenigsegg_gemera.jpg",
  },
  {
    id: 172,
    name: "Jeep Renegade",
    price: 25000,
    brand: "Jeep",
    type: ["family", "suv"],
    image: "../image/jeep_renegade.jpg",
  },
  {
    id: 173,
    name: "Jeep Compass",
    price: 30000,
    brand: "Jeep",
    type: ["family", "suv"],
    image: "../image/jeep_compass.jpg",
  },
  {
    id: 174,
    name: "Jeep Cherokee",
    price: 35000,
    brand: "Jeep",
    type: ["family", "suv"],
    image: "../image/jeep_cherokee.jpg",
  },
  {
    id: 175,
    name: "Jeep Grand Cherokee",
    price: 50000,
    brand: "Jeep",
    type: ["family", "suv"],
    image: "../image/jeep_grand_cherokee.jpg",
  },
  {
    id: 176,
    name: "Jeep Wrangler",
    price: 40000,
    brand: "Jeep",
    type: ["family", "suv"],
    image: "../image/jeep_wrangler.jpg",
  },
  {
    id: 177,
    name: "Jeep Gladiator",
    price: 50000,
    brand: "Jeep",
    type: ["family", "suv"],
    image: "../image/jeep_gladiator.jpg",
  },
  {
    id: 178,
    name: "Jeep Wagoneer",
    price: 70000,
    brand: "Jeep",
    type: ["family", "suv"],
    image: "../image/jeep_wagoneer.jpg",
  },
  {
    id: 179,
    name: "Jeep Grand Wagoneer",
    price: 90000,
    brand: "Jeep",
    type: ["family", "suv"],
    image: "../image/jeep_grand_wagoneer.jpg",
  },
  {
    id: 180,
    name: "Jeep Avenger",
    price: 40000,
    brand: "Jeep",
    type: ["family", "electric"],
    image: "../image/jeep_avenger.jpg",
  },
  {
    id: 181,
    name: "Jeep Wrangler 4xe",
    price: 55000,
    brand: "Jeep",
    type: ["family", "electric"],
    image: "../image/jeep_wrangler_4xe.jpg",
  },
  {
    id: 182,
    name: "Jeep Grand Cherokee 4xe",
    price: 70000,
    brand: "Jeep",
    type: ["family", "electric"],
    image: "../image/jeep_grand_cherokee_4xe.jpg",
  },
  {
    id: 183,
    name: "Range Rover",
    price: 140000,
    brand: "Range Rover",
    type: ["family", "suv"],
    image: "../image/range_rover.jpg",
  },
  {
    id: 184,
    name: "Range Rover Sport",
    price: 100000,
    brand: "Range Rover",
    type: ["family", "suv", "sport"],
    image: "../image/range_rover_sport.jpg",
  },
  {
    id: 185,
    name: "Range Rover Velar",
    price: 80000,
    brand: "Range Rover",
    type: ["family", "suv"],
    image: "../image/range_rover_velar.jpg",
  },
  {
    id: 186,
    name: "Range Rover Evoque",
    price: 50000,
    brand: "Range Rover",
    type: ["family", "suv"],
    image: "../image/range_rover_evoque.jpg",
  },
  {
    id: 187,
    name: "Land Rover Defender",
    price: 70000,
    brand: "Land Rover",
    type: ["family", "suv"],
    image: "../image/land_rover_defender.jpg",
  },
  {
    id: 188,
    name: "Land Rover Discovery",
    price: 75000,
    brand: "Land Rover",
    type: ["family", "suv"],
    image: "../image/land_rover_discovery.jpg",
  },
  {
    id: 189,
    name: "Tesla Model S Plaid",
    price: 100000,
    brand: "Tesla",
    type: ["sport", "electric"],
    image: "../image/tesla_model_s_plaid.jpg",
  },
  {
    id: 190,
    name: "Tesla Model 3 Performance",
    price: 60000,
    brand: "Tesla",
    type: ["sport", "electric"],
    image: "../image/tesla_model_3_performance.jpg",
  },
  {
    id: 191,
    name: "Tesla Model Y",
    price: 60000,
    brand: "Tesla",
    type: ["family", "suv", "electric"],
    image: "../image/tesla_model_y.jpg",
  },
  {
    id: 192,
    name: "Tesla Model X",
    price: 90000,
    brand: "Tesla",
    type: ["family", "suv", "electric"],
    image: "../image/tesla_model_x.jpg",
  },
  {
    id: 193,
    name: "Tesla Cybertruck",
    price: 80000,
    brand: "Tesla",
    type: "electric",
    image: "../image/tesla_cybertruck.jpg",
  },
  {
    id: 194,
    name: "Tesla Roadster",
    price: 200000,
    brand: "Tesla",
    type: "electric",
    image: "../image/tesla_roadster.jpg",
  },
];
